class_name GutConstants

const TYPE_STRINGS = {
	TYPE_NIL : 'TYPE_NIL',
	TYPE_BOOL : 'TYPE_BOOL',
	TYPE_INT : 'TYPE_INT',
	TYPE_FLOAT : 'TYPE_FLOAT',
	TYPE_STRING : 'TYPE_STRING',
	TYPE_VECTOR2 : 'TYPE_VECTOR2',
	TYPE_VECTOR2I : 'TYPE_VECTOR2I',
	TYPE_RECT2 : 'TYPE_RECT2',
	TYPE_RECT2I : 'TYPE_RECT2I',
	TYPE_VECTOR3 : 'TYPE_VECTOR3',
	TYPE_VECTOR3I : 'TYPE_VECTOR3I',
	TYPE_TRANSFORM2D : 'TYPE_TRANSFORM2D',
	TYPE_VECTOR4 : 'TYPE_VECTOR4',
	TYPE_VECTOR4I : 'TYPE_VECTOR4I',
	TYPE_PLANE : 'TYPE_PLANE',
	TYPE_QUATERNION : 'TYPE_QUATERNION',
	TYPE_AABB : 'TYPE_AABB',
	TYPE_BASIS : 'TYPE_BASIS',
	TYPE_TRANSFORM3D : 'TYPE_TRANSFORM3D',
	TYPE_PROJECTION : 'TYPE_PROJECTION',
	TYPE_COLOR : 'TYPE_COLOR',
	TYPE_STRING_NAME : 'TYPE_STRING_NAME',
	TYPE_NODE_PATH : 'TYPE_NODE_PATH',
	TYPE_RID : 'TYPE_RID',
	TYPE_OBJECT : 'TYPE_OBJECT',
	TYPE_CALLABLE : 'TYPE_CALLABLE',
	TYPE_SIGNAL : 'TYPE_SIGNAL',
	TYPE_DICTIONARY : 'TYPE_DICTIONARY',
	TYPE_ARRAY : 'TYPE_ARRAY',
	TYPE_PACKED_BYTE_ARRAY : 'TYPE_PACKED_BYTE_ARRAY',
	TYPE_PACKED_INT32_ARRAY : 'TYPE_PACKED_INT32_ARRAY',
	TYPE_PACKED_INT64_ARRAY : 'TYPE_PACKED_INT64_ARRAY',
	TYPE_PACKED_FLOAT32_ARRAY : 'TYPE_PACKED_FLOAT32_ARRAY',
	TYPE_PACKED_FLOAT64_ARRAY : 'TYPE_PACKED_FLOAT64_ARRAY',
	TYPE_PACKED_STRING_ARRAY : 'TYPE_PACKED_STRING_ARRAY',
	TYPE_PACKED_VECTOR2_ARRAY : 'TYPE_PACKED_VECTOR2_ARRAY',
	TYPE_PACKED_VECTOR3_ARRAY : 'TYPE_PACKED_VECTOR3_ARRAY',
	TYPE_PACKED_COLOR_ARRAY : 'TYPE_PACKED_COLOR_ARRAY',
	TYPE_PACKED_VECTOR4_ARRAY : 'TYPE_PACKED_VECTOR4_ARRAY',
	TYPE_MAX : 'TYPE_MAX',
}


static var TYPE_KEYWORDS = {
	TYPE_NIL : 'null',
	TYPE_BOOL : 'bool',
	TYPE_INT : 'int',
	TYPE_FLOAT : 'float',
}



static func _static_init() -> void:
	for key in TYPE_STRINGS:
		if(!TYPE_KEYWORDS.has(key)):
			var n : String = TYPE_STRINGS[key].to_lower()
			n = n.lstrip("type_")
			TYPE_KEYWORDS[key] = n.to_pascal_case()
