extends 'res://addons/gut/test.gd'
# ------------------------------------------------------------------------------
# These tests are used to test the output generated by parameterized
# tests.  These are only for visually verifying output formatting.
# ------------------------------------------------------------------------------

func test_no_parameters():
	assert_true(true, 'this passes')

func test_multiple_passing_no_params():
	assert_true(true)
	gut.p('something')
	assert_false(false)

func test_multiple_failing_no_params():
	assert_false(true)
	assert_true(false)

func test_basic_array(p=use_parameters([1, 2, 1, 4])):
	assert_eq(p, 1)

func test_all_passing(p=use_parameters([[1, 2], [3, 4], [5, 6]])):
	assert_eq(p[0], p[1 -1])

